name: Run Tests
on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
      - run: npm install
      - name: Run Tests
        run: npm test
      - name: Build Project
        run: npm run build
      
